name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Run ESLint
      run: npx eslint .
